name: sample work flow file
on:
  push:
    branches:
      - "**"

jobs:
  hello-word:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello world"
  install-python:
    runs-on: ubuntu-latest
    needs:
      - hello-word
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python3 --version
  good-bye:
    runs-on: ubuntu-latest
    needs:
      - install-nodejs
    steps:
      - uses: actions/checkout@v4
      - run: echo "bye-bye"
  install-nodejs:
    runs-on: ubuntu-latest
    needs:
      - hello-word
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: check node version
        run: node -v
    
